site_name: 07th-Mod - User Wiki
site_url: https://07th-mod.com/
repo_url: https://github.com/07th-mod
repo_name: 07th-Mod (Organization)
copyright: All Nipahs Reserved
site_dir: wiki
edit_uri: 'wiki/edit/master/docs'
nav:
    - Home: index.md
    - <b>Higurashi</b>:
        - 1. Intro: Higurashi/Higurashi-Getting-started.md
        - 2a. Installer: Higurashi/Higurashi-Part-1---Voice-and-Graphics-Patch.md
        - 2b. Manual Installation: Higurashi/Manual-Installation.md
        - 2c. Shortcuts and Settings: Higurashi/Higurashi-Part-2---Patch-configuration-and-keyboard-shortcuts.md
        - 3. FAQ: Higurashi/FAQ.md
        - 3a. Linux & Steam Deck FAQ: Higurashi/FAQ-linux-steam-deck.md
        - 3b. BGM/SE FAQ: Higurashi/BGM-SE-FAQ.md
        - 3c. Miotsukushi FAQ: Higurashi/MiotsukushiFAQ.md
        - 4. Getting Support: Higurashi/support.md
        - 5. Uninstalling Mod & Game: Higurashi/Uninstall.md
        - 6. Other Mods: Higurashi/other-mods.md
    - <b>Umineko</b>:
        - 1. Intro (START HERE): Umineko/Umineko-Getting-started.md
        - 2. Mod Options: Umineko/Umineko-Mod-Options.md
        - 3a. Cross-Platform Installer: Umineko/Umineko-Part-3a-Cross-Platform-Installer.md
        - 3b. Manual Voice and Graphics : Umineko/Umineko-Part-1---Voice-and-Graphics-Patch.md
        - 3c. Manual Voices-only : Umineko/Umineko-Part-1.1---Voices-only-Patch.md
#        - 4. Umineko Tsubasa, Hane and Saku: Umineko/Tsubasa-Hane.md
        - 5. FAQ/Troubleshooting: Umineko/Umineko-Part-0-TroubleShooting-and-FAQ.md
        - 6. Getting Support: Umineko/support.md
        - 7. Uninstalling Mod & Game: Umineko/Uninstall.md
    - <b>Installer</b>:
        - 1. FAQ: Installer/faq.md
        - 2. Getting support: Installer/support.md
        - Power User Installation: Installer/power-users.md
    - Rules: Rules.md
    - Support and Reporting Issues: Support.md
    - Contribution Guide: Beginners-guide.md
    - Credits: Credits.md
    - Higurashi Developer Information:
        - Overview:
            - Introduction: developer/overview/introduction.md
            - Features: developer/overview/features.md
            - Preparing a New Chapter: developer/overview/overview.md
            - Patch Folder Structure: developer/overview/patch-folder-structure.md
        - Higurashi Patch Compiler: developer/patch-compiler/how-to-use-higurashi-patch-compiler.md
        - Game Scripting:
            - Scripting Tutorial: developer/scripting/on-scripting.md
            - Mod Syntax Reference: developer/scripting/syntax.md
            - BGM & SE Scripting: developer/scripting/bgm-se-scripting.md
        - Translation Work:
            - Introduction: developer/translation/introduction.md
            - Resources and Guidelines: developer/translation/resources-and-guidelines.md
            - Console Exclusive Content: developer/translation/console-exclusive-content.md
            - Censorship / Script Changes: developer/translation/censorship-script-changes.md
        - Graphical Work:
            - PSD Files, Templates: developer/graphics/psd-files-templates.md
            - Resources, Technical Details: developer/graphics/resources-technical-details.md
            - Sunset/Night Filters: developer/graphics/sunset-night-filters.md
            - Mangagamer Sprite Edits: developer/graphics/mangagamer-sprite-edits.md
            - Background/Image Panning: developer/graphics/background-image-panning.md
        - UI Editing Scripts:
            - Overview: developer/sharedassets/overview.md
            - Usage: developer/sharedassets/ui-editing-scripts.md
        - Voices:
            - Voice Details: developer/voice/voice-details.md
            - Automated Voice Inserter: developer/voice/automated-voice-inserter.md
            - Manual Work Details: developer/voice/manual-work-details.md
        - DLL Modding:
            - Overview: developer/dll/overview.md
            - Modded engine flags: developer/dll/modded-engine-flags.md
        - Misc:
            - Git Line Endings: developer/misc/git-line-endings.md
        - Installer:
            - installData.json: developer/installer/install-data-json.md
        - Legacy Pages (out of date):
            - Old Batch File Installer: developer/legacy/code-overview.md
            - Old Advanced Installer: developer/legacy/technical-details.md
            - Adv Mode and Lipsync: developer/legacy/adv-mode-and-lipsync.md

theme:
  name: material
  features:
    #- navigation.tabs
    - navigation.instant
plugins:
   - search
   - minify
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - attr_list
  - pymdownx.snippets:
      base_path: docs/Snippets
      check_paths: true
